<?php

$bannerslider = $block->getActiveBanners();

?>

<article id="slider">
    <?php $i=1;  foreach($bannerslider as $index => $banner):  ?>
        <input <?php if($i == 1): ?> checked="checked" <?php endif ?> type=radio name=slider id=<?php echo 'slide'. $i ?> />
    <?php  $i++; endforeach;   ?>
    <div id=slides>
        <div id=overflow>
            <div class=inner>
                <?php  foreach($bannerslider as $index => $banner):  ?>
                    <article>
                        <?php if($banner->getUrl() != ''): ?><a href="<?php echo $banner->getUrl() ?>" target="_blank"><?php endif; ?>
                            <img src=<?php echo $block->getMediaDirectoryUrl().$banner->getBannerimage() ?> />
                        <?php if($banner->getUrl() != ''): ?></a><?php endif; ?>
                    </article>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div id=active>
        <?php $i=1; foreach($bannerslider as $index => $banner):  ?>
            <label for=<?php echo 'slide'. $i ?>></label>
        <?php $i++;  endforeach;   ?>
    </div>
</article>

<style type="text/css">
input[type=radio] {
	display: none;
}
</style>